# Site settings
author: Osagie Obaretin
title: Why did you decide to study Software Engineering?
header-img: img/home-bg.png
email: osagie.codes@gmail.com
copyright_name: Osagie Obaretin
description: > # this means to ignore newlines until "baseurl:"
  Why did you decide to study Software Engineering?
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  oobaretin

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
